export default {
    MODEL_LOAD_COMPLETED: "MODEL_LOAD_COMPLETED",
    DEVICE_SETTINGS_CHANGED: "DEVICE_SETTINGS_CHANGED",

    LEVELS_TREE_MOUSE_OVER: "LT_NODE_MOUSE_OVER",
    LEVELS_TREE_MOUSE_OUT: "LT_NODE_MOUSE_OUT",
    LEVELS_TREE_MOUSE_CLICK: "LT_NODE_MOUSE_CLICK",

    DEVICE_TREE_EXPAND_EVENT: "DT_NODE_EXPAND_EVENT",
}
