export default {
    MODEL_LOAD_COMPLETED: "MODEL_LOAD_COMPLETED",
    RENDER_SETTINGS_CHANGED: "RENDER_SETTINGS_CHANGED",

    GROUP_SELECTION_MOUSE_OVER: "GROUP_SELECTION_MOUSE_OVER",
    GROUP_SELECTION_MOUSE_OUT: "GROUP_SELECTION_MOUSE_OUT",
    GROUP_SELECTION_MOUSE_CLICK: "GROUP_SELECTION_MOUSE_CLICK",

    DEVICE_TREE_EXPAND_EVENT: "DT_NODE_EXPAND_EVENT",

    VIEWABLES_LOADED: "VIEWABLES_LOADED"
};
